import CountryListItem from '@/models/countryListItem';
import Head from 'next/head'
import { Countries } from '../components/countries'
export default function Home() {

  const countryListIems : CountryListItem[] = 
    [
      {
        code: 'US',
        name: 'United States of America'
      },
      {
        code: 'UA',
        name: 'UKraine'
      },
    ]
  ;
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          <Countries countryListItems={countryListIems} ></Countries>
        </div>
    </>
  )
}
