import CountryListItem from '@/models/countryListItem';
import { ApolloClient, InMemoryCache } from '@apollo/client';
import { NextPageContext } from 'next';
import Head from 'next/head'
import { Countries } from '../components/countries'



  // const client = new ApolloClient({
  //   uri: "https://countries.trevorblades.com/graphql",
  //   cache: new InMemoryCache()
  // });  
export default function Index(data) {
  console.log("props:"+data.countryListIems[0].code);
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          <Countries countryListItems={data.countryListIems} ></Countries>
        </div>
    </>
  );
}

export async function getServerSideProps(context: NextPageContext) {
  console.log("Invoked");

  const countryListIems : CountryListItem[] = 
    [
      {
        code: 'US',
        name: 'United States of America'
      },
      {
        code: 'UA',
        name: 'UKraine'
      },
    ];  

  return {
      props: {
        countryListIems : countryListIems
      }
    }
 }
    